# @file python3check.yml
---
name: Python3 syntax check

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  python3-pywbem-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install latest ilorest from pip
      run: |
        sudo apt-get install -qq -yy python3 python3-pip
        pip3 install ilorest
    - name: Launch plugin with --help
      run: |
        ./check_ilorest.py --help
